name: Lint mix project

on:
  workflow_call:
    inputs:
      elixirs:
        type: string
        default: "[\"1.14.x\"]"
      erlangs:
        type: string
        default: "[\"25.x\"]"
      apt-packages:
        type: string
        default: ""

env:
  MIX_ENV: test

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        elixir: ${{ fromJSON(inputs.elixirs) }}
        otp: ${{ fromJSON(inputs.erlangs) }}
        exclude:
          - elixir: 1.12.x
            otp: 25.x
          - elixir: 1.14.x
            otp: 23.x
    steps:
    - name: Install apt packages
      if: inputs.apt-packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ inputs.apt-packages }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}
    - name: Disable compile warnings
      run: echo "::remove-matcher owner=elixir-mixCompileWarning::"
    - name: Retrieve mix dependencies cache
      uses: actions/cache@v3
      id: mix-cache
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ matrix.otp }}-mix-${{ matrix.elixir }}-
    - name: Install mix dependencies
      if: steps.mix-cache.outputs.cache-hit != 'true'
      run: |
        mix deps.get
        mix deps.compile
    - name: Compile code
      run: mix compile --warnings-as-errors
    - name: Check for unused dependencies
      run: mix deps.unlock --check-unused
    - name: Check formatting
      run: mix format --check-formatted
    - name: Run credo
      run: mix credo --strict
    - name: Retrieve PLT cache
      uses: actions/cache@v3
      id: plt-cache
      with:
        path: priv/plts
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plts-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ matrix.otp }}-plts-${{ matrix.elixir }}-
    - name: Create PLTs
      if: steps.plt-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p priv/plts
        mix dialyzer --plt
    - name: Run dialyzer
      run: mix dialyzer --no-check
