name: Test mix project

on:
  workflow_call:
    inputs:
      elixirs:
        type: string
        default: "[\"1.16.x\", \"1.17.x\", \"1.18.x\"]"
      erlangs:
        type: string
        default: "[\"25.x\", \"26.x\", \"27.x\"]"
      apt-packages:
        type: string
        default: ""

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        elixir: ${{ fromJSON(inputs.elixirs) }}
        otp: ${{ fromJSON(inputs.erlangs) }}
        exclude:
          - elixir: 1.15.x
            otp: 27.x
          - elixir: 1.16.x
            otp: 27.x
    steps:
    - name: Install apt packages
      if: inputs.apt-packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ inputs.apt-packages }}
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}
    # This will disable warnings during dependency compilation, but since we
    # use --warnings-as-errors below for our own code, we'll see any warnings
    # generated by our own code
    - name: Disable compile warnings
      run: echo "::remove-matcher owner=elixir-mixCompileWarning::"
    - name: Retrieve mix dependencies cache
      uses: actions/cache@v4
      id: mix-cache
      with:
        path: |
          deps
          _build
        key: test-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: test-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-
    - name: Install mix dependencies
      if: steps.mix-cache.outputs.cache-hit != 'true'
      run: |
        mix deps.get
        mix deps.compile
    - name: Compile code
      run: mix compile --warnings-as-errors
    - name: Run tests
      run: mix test
